application.id=idempotent-writer-reader-app
bootstrap.servers=localhost:9092
input.topic=pattern.idempotent-writer-reader.in
writer.topic=pattern.idempotent-writer-reader.writer
output.topic=pattern.idempotent-writer-reader.out
dlq.topic=pattern.idempotent-writer-reader.dlq
