alpha.topic=pattern.event-collaboration.alpha
beta.topic=pattern.event-collaboration.beta
joined.topic=pattern.event-collaboration.joined
late.topic=pattern.event-collaboration.late
collaboration.lateness.ms=5000
