application.id=logical-and-multisignal-app
bootstrap.servers=localhost:9092
input.topic=pattern.logical-and-multisignal.in
output.topic=pattern.logical-and-multisignal.out
expired.topic=pattern.logical-and-multisignal.expired
correlation.window.ms=60000
