application.id=claim-check-app
bootstrap.servers=localhost:9092
input.topic=pattern.claim-check.in
references.topic=pattern.claim-check.refs
output.topic=pattern.claim-check.out
dlq.topic=pattern.claim-check.dlq
