application.id=event-chunking-app
bootstrap.servers=localhost:9092
input.topic=pattern.event-chunking.in
chunk.topic=pattern.event-chunking.chunks
output.topic=pattern.event-chunking.out
expired.topic=pattern.event-chunking.expired
chunk.size=128
chunk.timeout.ms=60000
