application.id=event-gateway-connect-app
bootstrap.servers=localhost:9092
input.topic=pattern.event-gateway-connect.in
output.topic=pattern.event-gateway-connect.out
retry.topic=pattern.event-gateway-connect.retry
dlq.topic=pattern.event-gateway-connect.dlq
gateway.retry.max=3
gateway.retry.backoff.ms=5000
